Algoritmo "Contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hudson Neves
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luis Eduardo de Sousa
// Data atual  : 08/05/2025
Var
// Seção de Declarações das variáveis 
     i:  inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     i <- 1
     enquanto i <= 10 faca
     escreval(i)
     i <- i + 1
     fimenquanto

Fimalgoritmo